version: '3.9'
services:
  api:
    container_name: go-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - "1312:1312"
    environment:
      - SQL_HOST=mysql
      - SQL_USER=root
      - SQL_PASSWORD=root1234
      - SQL_DB=go-crud-simple-cicd
      - SQL_PORT=3306

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=go-crud-simple-cicd
    volumes:
      - database:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database:
