name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true 
          tags: achmadrizkinf298/go-crud-simple-cicd

  deployment:
    needs: build
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            # Check Docker version to ensure it's installed
            docker --version

            # Pull the latest MySQL and app images
            docker pull mysql:latest
            docker pull achmadrizkinf298/go-crud-simple-cicd:latest

            # Create the backend network
            docker network create backend || true

            # Stop and remove any existing containers (if they exist)
            docker stop mysql-container || true
            docker rm mysql-container || true
            docker stop go-crud-simple-cicd || true
            docker rm go-crud-simple-cicd || true

            # Run MySQL container
            docker run -d \
              --name mysql-container \
              --network backend \
              -e MYSQL_ROOT_PASSWORD=root1234 \
              -e MYSQL_DATABASE=go_crud_simple_cicd \
              -e MYSQL_USER=root \
              -e MYSQL_PASSWORD=root1234 \
              -p 3306:3306 \
              --volume mysql_data:/var/lib/mysql \
              mysql:latest

            # Run the App container (depends on MySQL container)
            docker run -d \
              --name go-crud-simple-cicd \
              --network backend \
              -e SQL_HOST=mysql-container \
              -e SQL_PORT=3306 \
              -e SQL_USER=root \
              -e SQL_PASSWORD=root1234 \
              -e SQL_DB=go_crud_simple_cicd \
              -p 1312:1312 \
              achmadrizkinf298/go-crud-simple-cicd:latest