name: CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: true 
          tags: achmadrizkinf298/go-crud-simple-cicd

  deployment:
    needs: build
    environment: main
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            whoami
            docker stop go-crud-simple-cicd || true && docker rm go-crud-simple-cicd || true

            docker pull mysql:latest
            docker pull achmadrizkinf298/go-crud-simple-cicd:latest

            docker run -d --name mysql-db -p 3306:3306 \ -e MYSQL_ROOT_PASSWORD=root1234 \ -e MYSQL_DATABASE=go-crud-simple-cicd \ mysql:latest

            # Wait for MySQL to initialize (give it some time to set up)
            echo "Waiting for MySQL to start..."
            sleep 20

            docker run -d -p 1312:1312 --name go-crud-simple-cicd achmadrizkinf298/go-crud-simple-cicd
            
            echo "Containers are up and running."